// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace OOP_lab2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OOP_lab2.Class.Technic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Technics", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("OOP_lab2.Class.Computer", b =>
                {
                    b.HasBaseType("OOP_lab2.Class.Technic");

                    b.Property<string>("ModelProcessor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ram")
                        .HasColumnType("integer");

                    b.Property<int?>("TechnicId")
                        .HasColumnType("integer");

                    b.HasIndex("TechnicId")
                        .IsUnique();

                    b.ToTable("Computers", (string)null);
                });

            modelBuilder.Entity("OOP_lab2.Class.Smartfon", b =>
                {
                    b.HasBaseType("OOP_lab2.Class.Technic");

                    b.Property<int>("CameraMP")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCall")
                        .HasColumnType("boolean");

                    b.Property<string>("Manufactures")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TechnicId")
                        .HasColumnType("integer");

                    b.HasIndex("TechnicId")
                        .IsUnique();

                    b.ToTable("Smartfons", (string)null);
                });

            modelBuilder.Entity("OOP_lab2.Class.Computer", b =>
                {
                    b.HasOne("OOP_lab2.Class.Technic", null)
                        .WithOne()
                        .HasForeignKey("OOP_lab2.Class.Computer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OOP_lab2.Class.Technic", "Technic")
                        .WithOne("Computer")
                        .HasForeignKey("OOP_lab2.Class.Computer", "TechnicId");

                    b.Navigation("Technic");
                });

            modelBuilder.Entity("OOP_lab2.Class.Smartfon", b =>
                {
                    b.HasOne("OOP_lab2.Class.Technic", null)
                        .WithOne()
                        .HasForeignKey("OOP_lab2.Class.Smartfon", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OOP_lab2.Class.Technic", "Technic")
                        .WithOne("Smartfon")
                        .HasForeignKey("OOP_lab2.Class.Smartfon", "TechnicId");

                    b.Navigation("Technic");
                });

            modelBuilder.Entity("OOP_lab2.Class.Technic", b =>
                {
                    b.Navigation("Computer");

                    b.Navigation("Smartfon");
                });
#pragma warning restore 612, 618
        }
    }
}
